"""empty message

Revision ID: 1457d9365d60
Revises: 
Create Date: 2025-09-17 12:09:32.151833

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1457d9365d60'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('theme_preference', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('email_notifications', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('auto_save', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('summary_length', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('items_per_page', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('items_per_page')
        batch_op.drop_column('summary_length')
        batch_op.drop_column('auto_save')
        batch_op.drop_column('email_notifications')
        batch_op.drop_column('theme_preference')

    # ### end Alembic commands ###
